<template>
  <div class="loadingio-spinner-spin-9a0k5ooqicd"><div class="ldio-w2hp18vt7p7">
  <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
  </div></div>
</template>



<style type="text/css">
@keyframes ldio-w2hp18vt7p7 {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.23,1.23);
  } 100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1,1);
  }
}
.ldio-w2hp18vt7p7 div > div {
  position: absolute;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: #2e4a4f;
  animation: ldio-w2hp18vt7p7 1s linear infinite;
}.ldio-w2hp18vt7p7 div:nth-child(1) > div {
  left: 75px;
  top: 45px;
  animation-delay: -0.875s;
}
.ldio-w2hp18vt7p7 > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 80px 50px;
}.ldio-w2hp18vt7p7 div:nth-child(2) > div {
  left: 66px;
  top: 66px;
  animation-delay: -0.75s;
}
.ldio-w2hp18vt7p7 > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 71px 71px;
}.ldio-w2hp18vt7p7 div:nth-child(3) > div {
  left: 45px;
  top: 75px;
  animation-delay: -0.625s;
}
.ldio-w2hp18vt7p7 > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 50px 80px;
}.ldio-w2hp18vt7p7 div:nth-child(4) > div {
  left: 24px;
  top: 66px;
  animation-delay: -0.5s;
}
.ldio-w2hp18vt7p7 > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 29px 71px;
}.ldio-w2hp18vt7p7 div:nth-child(5) > div {
  left: 15px;
  top: 45px;
  animation-delay: -0.375s;
}
.ldio-w2hp18vt7p7 > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 20px 50px;
}.ldio-w2hp18vt7p7 div:nth-child(6) > div {
  left: 24px;
  top: 24px;
  animation-delay: -0.25s;
}
.ldio-w2hp18vt7p7 > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 29px 29px;
}.ldio-w2hp18vt7p7 div:nth-child(7) > div {
  left: 45px;
  top: 15px;
  animation-delay: -0.125s;
}
.ldio-w2hp18vt7p7 > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 50px 20px;
}.ldio-w2hp18vt7p7 div:nth-child(8) > div {
  left: 66px;
  top: 24px;
  animation-delay: 0s;
}
.ldio-w2hp18vt7p7 > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 71px 29px;
}
.loadingio-spinner-spin-9a0k5ooqicd {
  width: 94px;
  height: 94px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-w2hp18vt7p7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.94);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-w2hp18vt7p7 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>