<template>
    <div class="animation-container">
        <div class="loadingio-spinner-blocks-xvd05hvm8cs"><div class="ldio-8sn0qz5ub34">
        <div style='left:38px;top:38px;animation-delay:0s'></div><div style='left:80px;top:38px;animation-delay:0.125s'></div><div style='left:122px;top:38px;animation-delay:0.25s'></div><div style='left:38px;top:80px;animation-delay:0.875s'></div><div style='left:122px;top:80px;animation-delay:0.375s'></div><div style='left:38px;top:122px;animation-delay:0.75s'></div><div style='left:80px;top:122px;animation-delay:0.625s'></div><div style='left:122px;top:122px;animation-delay:0.5s'></div>
        </div></div>
    </div>
</template>

<script>
export default {

}
</script>
<style>
@keyframes ldio-8sn0qz5ub34 {
  0% { background: #1f8c8c }
  12.5% { background: #1f8c8c }
  12.625% { background: #24449d }
  100% { background: #24449d }
}
.ldio-8sn0qz5ub34 div {
  position: absolute;
  width: 40px;
  height: 40px;
  background: #24449d;
  animation: ldio-8sn0qz5ub34 1s linear infinite;
}
.loadingio-spinner-blocks-xvd05hvm8cs {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-8sn0qz5ub34 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(.5);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-8sn0qz5ub34 div { box-sizing: content-box; }
/* generated by https://loading.io/ */

.animation-container{
    display:flex;
    justify-content:center;
}


</style>