<template>
  
  <div class="loadingio-spinner-rolling-lr6fki7xex8"><div class="ldio-ekg6tteb0tq">

  <div></div>
  </div></div>
</template>

<style type="text/css">
@keyframes ldio-ekg6tteb0tq {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-ekg6tteb0tq div {
  position: absolute;
  width: 46px;
  height: 46px;
  border: 8px solid #1fb966;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-ekg6tteb0tq div {
  animation: ldio-ekg6tteb0tq 0.9174311926605504s linear infinite;
  top: 50px;
  left: 50px
}
.loadingio-spinner-rolling-lr6fki7xex8 {
  width: 24px;
  height: 24px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-ekg6tteb0tq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.24);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ekg6tteb0tq div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>